In [17]:
from sqlalchemy import create_engine
import pandas as pd

In [18]:
db_url = "postgresql://readonly_user:ZpUSlM6Hdsc1tp14@91.243.71.68:5870/fdrive"
engine = create_engine(db_url)

In [19]:
query = """
SELECT table_name
FROM information_schema.tables
WHERE table_schema='raw'
"""

tables = pd.read_sql(query, engine)
tables

                        table_name
0                      _column_map
1                     fdrive_tyres
2             pitstopshop_products
3                    price_history
4                     quality_gaps
5                      _load_files
6               almatyres_products
7                 carcity_products
8                      fdrive_oils
9  marketplace_products_normalized

In [24]:
from sqlalchemy import create_engine
import pandas as pd

db_url = "postgresql://readonly_user:ZpUSlM6Hdsc1tp14@91.243.71.68:5870/fdrive"
engine = create_engine(db_url)

df = pd.read_sql("""
SELECT * FROM raw.marketplace_products_normalized
LIMIT 100
""", engine)

print(df.shape)
print(df["c007_category"].value_counts())

(100, 46)
c007_category
Моторные масла                91
Мотошины                       2
Шины                           2
Аккумуляторы                   2
Шины для спецтехники           2
Автомобильные аккумуляторы     1
Name: count, dtype: int64

In [25]:
# 1.marketplace (forte + satu)
marketplace = pd.read_sql("""
SELECT
    c001_sku_id as sku_id,
    c002_source as source,
    c008_product_name as product_name,
    c009_normalized_name as normalized_name,
    c007_category as category,
    c018_brand as brand,
    c020_viscosity as viscosity,
    c021_volume_liters as volume,
    c033_width as width,
    c034_profile as profile,
    c035_diameter as diameter,
    c036_season as season,
    c040_filter_type as filter_type,
    c043_oem_number as oem_number,
    c026_capacity_ah as capacity_ah,
    c027_voltage_v as voltage_v
FROM raw.marketplace_products_normalized
""", engine)

# 2.carcity
carcity = pd.read_sql("""
SELECT
    CONCAT('carcity:', c002_source_product_id) as sku_id,
    'carcity' as source,
    c007_name as product_name,
    c007_name as normalized_name,
    c006_category_leaf as category,
    c008_brand as brand,
    c040_viscosity as viscosity,
    c041_volume_liters as volume,
    c027_tire_width as width,
    c028_tire_profile as profile,
    c029_tire_diameter as diameter,
    c030_season as season,
    c050_filter_type as filter_type,
    c010_oem_numbers as oem_number,
    c052_capacity_ah as capacity_ah,
    c053_voltage_v as voltage_v
FROM raw.carcity_products
""", engine)

# 3.pitstopshop
pitstop = pd.read_sql("""
SELECT
    CONCAT('pitstop:', c002_source_product_id) as sku_id,
    'pitstopshop' as source,
    c007_name as product_name,
    c007_name as normalized_name,
    c006_category_leaf as category,
    c008_brand as brand,
    c042_viscosity as viscosity,
    c043_volume_liters as volume,
    c027_tire_width as width,
    c028_tire_profile as profile,
    c029_tire_diameter as diameter,
    c030_season as season,
    c052_filter_type as filter_type,
    c010_oem_numbers as oem_number,
    c054_capacity_ah as capacity_ah,
    c055_voltage_v as voltage_v
FROM raw.pitstopshop_products
""", engine)

# 4.fdrive oils
fdrive_oils = pd.read_sql("""
SELECT
    CONCAT('fdrive_oil:', c001_product_id) as sku_id,
    'fdrive' as source,
    c002_name as product_name,
    c002_name as normalized_name,
    c007_category as category,
    c010_brand_name as brand,
    c016_klass_vyazkosti_sae as viscosity,
    c015_obem_upakovki_l as volume,
    NULL as width,
    NULL as profile,
    NULL as diameter,
    NULL as season,
    NULL as filter_type,
    NULL as oem_number,
    NULL as capacity_ah,
    NULL as voltage_v
FROM raw.fdrive_oils
""", engine)

# 5.fdrive tyres
fdrive_tyres = pd.read_sql("""
SELECT
    CONCAT('fdrive_tyre:', c001_product_id) as sku_id,
    'fdrive' as source,
    c002_name as product_name,
    c002_name as normalized_name,
    c006_category as category,
    c007_brand as brand,
    NULL as viscosity,
    NULL as volume,
    c018_width as width,
    c019_height as profile,
    c020_diameter as diameter,
    c016_season as season,
    NULL as filter_type,
    NULL as oem_number,
    NULL as capacity_ah,
    NULL as voltage_v
FROM raw.fdrive_tyres
""", engine)

# 6.almatyres
almatyres = pd.read_sql("""
SELECT
    CONCAT('almatyres:', c002_product_id) as sku_id,
    'almatyres' as source,
    c003_name as product_name,
    c003_name as normalized_name,
    c007_category as category,
    c011_proizvoditel as brand,
    NULL as viscosity,
    NULL as volume,
    c017_shirina_shiny as width,
    c030_vysota_profilya_shiny as profile,
    c024_posadochnyy_diametr_shiny as diameter,
    c015_sezonnost_shin as season,
    NULL as filter_type,
    NULL as oem_number,
    NULL as capacity_ah,
    NULL as voltage_v
FROM raw.almatyres_products
""", engine)

#CONCAT
df = pd.concat([marketplace, carcity, pitstop, fdrive_oils, fdrive_tyres, almatyres], ignore_index=True)
print(df.shape)
print(df["source"].value_counts())

(192420, 16)
source
pitstopshop     131086
carcity          43798
forte_market     10967
fdrive            5495
satu_kz            576
almatyres          498
Name: count, dtype: int64

In [26]:
df

,sku_id,source,product_name,normalized_name,category,brand,viscosity,volume,width,profile,diameter,season,filter_type,oem_number,capacity_ah,voltage_v
0,satu_kz:129790702,satu_kz,Моторное масло Castrol Vecton Long Drain 10W-4...,Моторное масло Castrol Vecton Long Drain 10W-4...,Моторные масла,Castrol,10W-40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,satu_kz:128166306,satu_kz,"Масло моторное дизельное М10ДМ, бочка 205 л",Масло моторное дизельное М10ДМ бочка 205 л,Моторные масла,Роснефть,NaN,205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,satu_kz:714546,satu_kz,Моторное масло SAE 15W40 PEMCO Disel G-4,Моторное масло SAE 15W-40 PEMCO Disel G-4,Моторные масла,Api,15W-40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,satu_kz:132007689,satu_kz,Моторное масло TOTAL RUBIA WORKS 1000 15W-40,Моторное масло TOTAL RUBIA WORKS 1000 15W-40,Моторные масла,Total,15W-40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,satu_kz:89669428,satu_kz,Масло 46 для компрессоров 20л,Масло 46 для компрессоров 20 л,Моторные масла,Total,NaN,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192415,almatyres:126082462,almatyres,Шина для спецтехники 11.2-24 12PR R 1W TT,Шина для спецтехники 11.2-24 12PR R 1W TT,"ALMATYRES > Шины, автошины > Шины для всех вид...",NaN,None,None,NaN,NaN,"24""",NaN,None,None,None,None
192416,almatyres:126082479,almatyres,"Шина для спецтехники 15,5-38 12PR TT R1W","Шина для спецтехники 15,5-38 12PR TT R1W","ALMATYRES > Шины, автошины > Шины для всех вид...",NaN,None,None,NaN,NaN,NaN,NaN,None,None,None,None
192417,almatyres:126082486,almatyres,Шина для спецтехники 20.8-38 14PR R 1W TT R1W,Шина для спецтехники 20.8-38 14PR R 1W TT R1W,"ALMATYRES > Шины, автошины > Шины для всех вид...",NaN,None,None,NaN,NaN,NaN,NaN,None,None,None,None
192418,almatyres:126082491,almatyres,Шина для спецтехники 6.50-10 10PR TT SC803,Шина для спецтехники 6.50-10 10PR TT SC803,"ALMATYRES > Шины, автошины > Шины для всех вид...",Gold,None,None,190 мм,NaN,NaN,NaN,None,None,None,None
192419,almatyres:126082498,almatyres,Шина для спецтехники 7.00-12 14PR TT SC804,Шина для спецтехники 7.00-12 14PR TT SC804,"ALMATYRES > Шины, автошины > Шины для всех вид...",NaN,None,None,NaN,NaN,"12""",NaN,None,None,None,None

In [27]:
print("=== marketplace ===")
print(marketplace["category"].value_counts())

print("=== carcity ===")
print(carcity["category"].value_counts())

print("=== pitstop ===")
print(pitstop["category"].value_counts())

print("=== fdrive oils ===")
print(fdrive_oils["category"].value_counts())

print("=== fdrive tyres ===")
print(fdrive_tyres["category"].value_counts())

print("=== almatyres ===")
print(almatyres["category"].value_counts())

=== marketplace ===
category
Шины                                7813
Автомобильные фильтры               2304
Моторное масло                       671
Аккумуляторы                         179
Моторные масла                       144
Автомобильные аккумуляторы           144
Шины для спецтехники                  95
Автомобильные фильтры, общее          61
Комплекты автомобильных фильтров      47
Фильтры салона                        36
Грузовые шины                         33
Мотошины                              11
Шины для легковых автомобилей          5
Name: count, dtype: int64
=== carcity ===
category
Воздушные фильтры                      11548
Шины для легковых авто                  7719
Масляные фильтры                        7625
Салонные фильтры                        6402
Топливные фильтры                       6237
Автомобильные моторные масла            1215
Трансмиссионные фильтры                  690
Трансмиссионные масла                    676
Шины для грузового транспорта            662
Шины для коммерческого транспорта        464
Аккумуляторные батареи                   199
Гидравлические фильтры                   134
Специальные масла                        100
Моторные масла для мототехники            59
Комплекты шин                             41
Моторные масла для лодочных моторов       23
Мотошины                                   4
Name: count, dtype: int64
=== pitstop ===
category
Легковые шины        120157
Грузовые шины          6035
Мото шины              3958
Сельхоз шины            726
Квадро шины (ATV)       210
Name: count, dtype: int64
=== fdrive oils ===
category
Масла и жидкости    235
Name: count, dtype: int64
=== fdrive tyres ===
category
Шины    5260
Name: count, dtype: int64
=== almatyres ===
category
ALMATYRES > Шины, автошины > Шины для сельхоз техники > Шины 10.0/80-12 Petlas TA-60                                              2
ALMATYRES > Шины, автошины > Шины для сельхоз техники > Шины 14.9-24 Petlas TA60 420/70-24                                        2
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шины для промышленного оборудования 15.5/80-24 REINFORCED TR-60    2
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шины для грейдеров 13.00-24 SG200                                  2
ALMATYRES > Шины, автошины > Мотошины > 3,00-8 38 А4 Л-369 Сельхозшина                                                            2
                                                                                                                                 ..
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шина для спецтехники 11.2-24 12PR R 1W TT                          1
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шина для спецтехники 15,5-38 12PR TT R1W                           1
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шина для спецтехники 20.8-38 14PR R 1W TT R1W                      1
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шина для спецтехники 6.50-10 10PR TT SC803                         1
ALMATYRES > Шины, автошины > Шины для всех видов спецтехники > Шина для спецтехники 7.00-12 14PR TT SC804                         1
Name: count, Length: 493, dtype: int64

In [28]:
category_map = {
    # oils
    "Моторное масло": "oils",
    "Моторные масла": "oils",
    "Автомобильные моторные масла": "oils",
    "Масла и жидкости": "oils",
    "Трансмиссионные масла": "oils",
    "Специальные масла": "oils",
    "Моторные масла для мототехники": "oils",
    "Моторные масла для лодочных моторов": "oils",

    # tyres
    "Шины": "tyres",
    "Шины для спецтехники": "tyres",
    "Шины для легковых авто": "tyres",
    "Шины для легковых автомобилей": "tyres",
    "Шины для грузового транспорта": "tyres",
    "Шины для коммерческого транспорта": "tyres",
    "Легковые шины": "tyres",
    "Грузовые шины": "tyres",
    "Мото шины": "tyres",
    "Мотошины": "tyres",
    "Сельхоз шины": "tyres",
    "Квадро шины (ATV)": "tyres",
    "Комплекты шин": "tyres",

    # filters
    "Автомобильные фильтры": "filters",
    "Автомобильные фильтры, общее": "filters",
    "Комплекты автомобильных фильтров": "filters",
    "Фильтры салона": "filters",
    "Воздушные фильтры": "filters",
    "Масляные фильтры": "filters",
    "Салонные фильтры": "filters",
    "Топливные фильтры": "filters",
    "Трансмиссионные фильтры": "filters",
    "Гидравлические фильтры": "filters",

    # batteries
    "Аккумуляторы": "batteries",
    "Автомобильные аккумуляторы": "batteries",
    "Аккумуляторные батареи": "batteries",
}

def map_almatyres_category(cat):
    if pd.isna(cat):
        return "unknown"
    cat = cat.lower()
    if "масл" in cat:
        return "oils"
    if "шин" in cat:
        return "tyres"
    if "фильтр" in cat:
        return "filters"
    if "аккумул" in cat:
        return "batteries"
    return "unknown"

df["category_clean"] = df["category"].map(category_map)
mask = df["source"] == "almatyres"
df.loc[mask, "category_clean"] = df.loc[mask, "category"].apply(map_almatyres_category)

print(df["category_clean"].value_counts())
print("Unknown:", df["category_clean"].isna().sum())

category_clean
tyres        153691
filters       35084
oils           3123
batteries       522
Name: count, dtype: int64
Unknown: 0

In [30]:
import re

def clean_text(text):
    if pd.isna(text):
        return ""
    text = text.lower()
    text = re.sub(r'[^\w\s]', ' ', text) 
    text = re.sub(r'\s+', ' ', text).strip() 
    return text

df["name_clean"] = df["normalized_name"].apply(clean_text)

In [31]:
oils_df = df[df["category_clean"] == "oils"].copy()
print(oils_df.shape)
print("\nЗаполненность полей:")
print(oils_df[["brand", "viscosity", "volume"]].notna().sum())

(3123, 18)

Заполненность полей:
brand        3123
viscosity    2299
volume       2973
dtype: int64

In [32]:
stop_words = ["моторное", "масло", "oil", "масла", "motor", "для", "двигателя"]

def remove_stop_words(text):
    if not text:
        return ""
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)


oils_df["name_matching"] = oils_df["name_clean"].apply(remove_stop_words)
print(oils_df[["normalized_name", "name_clean", "name_matching"]].head())

                                     normalized_name  \
0  Моторное масло Castrol Vecton Long Drain 10W-4...
1         Масло моторное дизельное М10ДМ бочка 205 л
2          Моторное масло SAE 15W-40 PEMCO Disel G-4
3       Моторное масло TOTAL RUBIA WORKS 1000 15W-40
4                     Масло 46 для компрессоров 20 л

                                          name_clean  \
0  моторное масло castrol vecton long drain 10w 4...
1         масло моторное дизельное м10дм бочка 205 л
2          моторное масло sae 15w 40 pemco disel g 4
3       моторное масло total rubia works 1000 15w 40
4                     масло 46 для компрессоров 20 л

                             name_matching
0  castrol vecton long drain 10w 40 e8 e11
1              дизельное м10дм бочка 205 л
2               sae 15w 40 pemco disel g 4
3            total rubia works 1000 15w 40
4                     46 компрессоров 20 л

In [10]:
from sentence_transformers import SentenceTransformer
print("OK!")

C:\Users\nazym\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

OK!

In [33]:
print(oils_df.columns.tolist())

['sku_id', 'source', 'product_name', 'normalized_name', 'category', 'brand', 'viscosity', 'volume', 'width', 'profile', 'diameter', 'season', 'filter_type', 'oem_number', 'capacity_ah', 'voltage_v', 'category_clean', 'name_clean', 'name_matching']

In [34]:
oils_df = df[df["category_clean"] == "oils"].copy()

oils_df["brand_clean"] = oils_df["brand"].fillna("unknown").str.lower().str.strip()
oils_df["viscosity_clean"] = oils_df["viscosity"].fillna("unknown").str.lower().str.strip()

def clean_volume(val):
    if pd.isna(val):
        return "unknown"
    val = str(val).lower().strip()
    val = val.replace("л", "").replace("l", "").replace("литр", "")
    val = val.replace(",", ".").strip()
    try:
        return str(round(float(val)))
    except:
        return "unknown"

def extract_oil_type(name):
    if pd.isna(name):
        return "unknown"
    name = name.lower()
    if "full synthetic" in name or "синтетическое" in name or "синтетик" in name:
        return "synthetic"
    elif "полусинтетическое" in name or "semi" in name:
        return "semi"
    elif "минеральное" in name or "mineral" in name:
        return "mineral"
    else:
        return "unknown"

oils_df["volume_clean"] = oils_df["volume"].apply(clean_volume)
oils_df["oil_type_clean"] = oils_df["name_clean"].apply(extract_oil_type)

oils_df["group_key"] = (
    oils_df["brand_clean"] + "_" +
    oils_df["viscosity_clean"] + "_" +
    oils_df["volume_clean"] + "_" +
    oils_df["oil_type_clean"]
)

print("Всего групп:", oils_df["group_key"].nunique())
print(oils_df["oil_type_clean"].value_counts())

Всего групп: 1212
oil_type_clean
unknown      1909
synthetic    1116
mineral        77
semi           21
Name: count, dtype: int64

In [35]:
from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Загружаем модель которая понимает русский
model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")

results = []

for group_key, group in oils_df.groupby("group_key"):
    if len(group) < 2:
        continue
    
    names = group["name_clean"].tolist()
    embeddings = model.encode(names)
    sim_matrix = cosine_similarity(embeddings)
    
    indices = group.index.tolist()
    for i in range(len(indices)):
        for j in range(i+1, len(indices)):
            
            # пропускаем если один и тот же источник
            if group.iloc[i]["source"] == group.iloc[j]["source"]:
                continue
                
            score = sim_matrix[i][j]
            if score > 0.7:
                results.append({
                    "sku_1": group.iloc[i]["sku_id"],
                    "sku_2": group.iloc[j]["sku_id"],
                    "name_1": group.iloc[i]["normalized_name"],
                    "name_2": group.iloc[j]["normalized_name"],
                    "source_1": group.iloc[i]["source"],
                    "source_2": group.iloc[j]["source"],
                    "group": group_key,
                    "score": round(score, 3)
                })

results_df = pd.DataFrame(results)
print(results_df.shape)
print(results_df.head(30))

C:\Users\nazym\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|█████████████████████████████████████████████████████████████| 199/199 [00:00<00:00, 2460.21it/s]

(723, 8)
                                                sku_1  \
0                                      carcity:612978
1                                      carcity:713057
2                                   satu_kz:108008416
3                                   satu_kz:107304109
4                                   satu_kz:107252062
5   forte_market:6548c779-edfb-11eb-ba47-0a580a02036a
6   forte_market:6548c779-edfb-11eb-ba47-0a580a02036a
7   forte_market:6548c779-edfb-11eb-ba47-0a580a02036a
8   forte_market:6548c779-edfb-11eb-ba47-0a580a02036a
9   forte_market:7eb302a1-edfb-11eb-bf86-0a580a02021a
10  forte_market:54646c29-e5ad-11eb-aba7-0a580a020865
11                                  satu_kz:126644374
12  forte_market:b52c5805-8e2f-11f0-8880-9af6307f8e62
13                                      carcity:88468
14                                      carcity:88468
15                                      carcity:88456
16                                      carcity:88456
17                                      carcity:88478
18                                      carcity:88467
19                                      carcity:88467
20                                      carcity:88453
21                                      carcity:88454
22                                      carcity:88454
23                                      carcity:88419
24                                      carcity:88419
25                                      carcity:88429
26                                      carcity:88429
27                                      carcity:88429
28                                      carcity:88451
29                                      carcity:88451

                                                sku_2  \
0                                    fdrive_oil:17137
1                                    fdrive_oil:17137
2   forte_market:97a92733-a5b2-11f0-8eaa-323109c6e470
3   forte_market:c4be1c01-4478-11f1-bb9f-926e19253b23
4   forte_market:c4be1c01-4478-11f1-bb9f-926e19253b23
5                                       carcity:63887
6                                       carcity:63874
7                                      carcity:112799
8                                      carcity:112800
9                                       carcity:63876
10                                    carcity:1174676
11  forte_market:2973dd3b-e5b0-11eb-acb9-0a580a02033a
12                                    carcity:1271602
13                                   fdrive_oil:16510
14                                   fdrive_oil:16510
15                                   fdrive_oil:16511
16                                   fdrive_oil:16503
17                                   fdrive_oil:16512
18                                   fdrive_oil:16512
19                                   fdrive_oil:16512
20                                   fdrive_oil:16496
21                                   fdrive_oil:16501
22                                   fdrive_oil:16501
23                                   fdrive_oil:16474
24                                   fdrive_oil:16474
25                                   fdrive_oil:16488
26                                   fdrive_oil:16483
27                                   fdrive_oil:16467
28                                   fdrive_oil:16488
29                                   fdrive_oil:16483

                                               name_1  \
0   Моторное масло Синтетическое Bardahl ХTRA 5W-3...
1   Моторное масло Синтетическое Bardahl XTC 5W-30...
2   Моторное масло Castrol Vecton Long Drain 10W-4...
3       Моторное масло Castrol Vecton 10W-40 E7 208 л
4   Моторное масло Castrol crb turbomax 10W-40 E4/...
5                       Fuchs Titan SuperSyn 5W-40 1L
6                       Fuchs Titan SuperSyn 5W-40 1L
7                       Fuchs Titan SuperSyn 5W-40 1L
8                       Fuchs Titan SuperSyn 5W-40 1L
9                       Fuchs Titan SuperSyn 5W-40 4L
10                        G-Energy Expert L 10W-40 1L
11           Моторное масло G-Energy Active 5W-40 1 л
12                       G-Energy Expert L 5W-40 205L
13  Масло моторное KORSON FULL SYNTHETIC 0W-20 C5 4 л
14  Масло моторное KORSON FULL SYNTHETIC 0W-20 C5 4 л
15  0W-30 FULL SYNTHETIC A3/B4 1л (синт. мотор. ма...
16  0W-30 FULL SYNTHETIC A3/B4 1л (синт. мотор. ма...
17  Моторное синтетическое масло Korson 0W-30 FULL...
18  Масло моторное KORSON FULL SYNTHETIC 0W-30 A3/...
19  Масло моторное KORSON FULL SYNTHETIC 0W-30 A3/...
20  Масло моторное KORSON FULL SYNTHETIC 0W-40 A3/...
21  Масло моторное KORSON FULL SYNTHETIC 0W-40 A3/...
22  Масло моторное KORSON FULL SYNTHETIC 0W-40 A3/...
23  Моторное полусинтетическое масло Korson 10W-40...
24  Моторное полусинтетическое масло Korson 10W-40...
25  5W-30 FULL SYNTHETIC A5/B5 1л (синт. мотор. ма...
26  5W-30 FULL SYNTHETIC A5/B5 1л (синт. мотор. ма...
27  5W-30 FULL SYNTHETIC A5/B5 1л (синт. мотор. ма...
28   Масло моторное KORSON FULL SYNTHETIC 5W-40 C3 1л
29   Масло моторное KORSON FULL SYNTHETIC 5W-40 C3 1л

                                               name_2      source_1  \
0   Синтетическое моторное масло Bardahl XTC 5W-30 5L       carcity
1   Синтетическое моторное масло Bardahl XTC 5W-30 5L       carcity
2         Castrol Vecton Long Drain E6/E9 10W-40 208L       satu_kz
3                  Castrol Magnatec A3/B4 10W-40 208L       satu_kz
4                  Castrol Magnatec A3/B4 10W-40 208L       satu_kz
5   FUCHS Моторное масло TITAN SUPERSYN LONGLIFE 5...  forte_market
6        FUCHS Моторное масло TITAN SUPERSYN 5W-40 1L  forte_market
7         Моторное масло FUCHS TITAN SYN SP 10W-40 1л  forte_market
8         FUCHS Моторное масло TITAN SYN SP 5W-40, 1L  forte_market
9        FUCHS Моторное масло TITAN SUPERSYN 5W-40 4L  forte_market
10  Масло моторное G-Energy Expert G 10W-40 API SG...  forte_market
11                 G-Energy Synthetic Active 5W-40 1L       satu_kz
12  Масло моторное универсальное всесезонное G-Ene...  forte_market
13  Синтетическое моторное масло KORSON 0W-20 4 л ...       carcity
14  Синтетическое моторное масло KORSON 0W-20 4 л ...       carcity
15  Синтетическое моторное масло KORSON 0W-30 1 л ...       carcity
16  Синтетическое моторное масло KORSON 0W-30 1 л ...       carcity
17  Синтетическое моторное масло KORSON 0W-30 4 л ...       carcity
18  Синтетическое моторное масло KORSON 0W-30 4 л ...       carcity
19  Синтетическое моторное масло KORSON 0W-30 4 л ...       carcity
20  Синтетическое моторное масло KORSON 0W-40 1 л ...       carcity
21  Синтетическое моторное масло KORSON 0W-40 4 л ...       carcity
22  Синтетическое моторное масло KORSON 0W-40 4 л ...       carcity
23  Полу-синтетическое моторное масло KORSON 10W-4...       carcity
24  Полу-синтетическое моторное масло KORSON 10W-4...       carcity
25  Синтетическое моторное масло KORSON 5W-30 1 л ...       carcity
26  Полу-синтетическое моторное масло KORSON 5W-30...       carcity
27  Синтетическое моторное масло KORSON 5W-30 1 л ...       carcity
28  Синтетическое моторное масло KORSON 5W-30 1 л ...       carcity
29  Полу-синтетическое моторное масло KORSON 5W-30...       carcity

        source_2                       group  score
0         fdrive   bardahl_5w-30_5_synthetic  0.967
1         fdrive   bardahl_5w-30_5_synthetic  0.990
2   forte_market  castrol_10w-40_208_unknown  0.852
3   forte_market  castrol_10w-40_208_unknown  0.720
4   forte_market  castrol_10w-40_208_unknown  0.704
5        carcity       fuchs_5w-40_1_unknown  0.834
6        carcity       fuchs_5w-40_1_unknown  0.866
7        carcity       fuchs_5w-40_1_unknown  0.746
8        carcity       fuchs_5w-40_1_unknown  0.770
9        carcity       fuchs_5w-40_4_unknown  0.869
10       carcity   g-energy_10w-40_1_unknown  0.829
11  forte_market    g-energy_5w-40_1_unknown  0.797
12       carcity  g-energy_5w-40_205_unknown  0.735
13        fdrive    korson_0w-20_4_synthetic  0.935
14        fdrive    korson_0w-20_4_synthetic  0.935
15        fdrive    korson_0w-30_1_synthetic  0.846
16        fdrive    korson_0w-30_1_synthetic  0.826
17        fdrive    korson_0w-30_4_synthetic  0.930
18        fdrive    korson_0w-30_4_synthetic  0.936
19        fdrive    korson_0w-30_4_synthetic  0.936
20        fdrive    korson_0w-40_1_synthetic  0.913
21        fdrive    korson_0w-40_4_synthetic  0.920
22        fdrive    korson_0w-40_4_synthetic  0.920
23        fdrive   korson_10w-40_1_synthetic  0.891
24        fdrive   korson_10w-40_1_synthetic  0.891
25        fdrive    korson_5w-30_1_synthetic  0.860
26        fdrive    korson_5w-30_1_synthetic  0.874
27        fdrive    korson_5w-30_1_synthetic  0.904
28        fdrive    korson_5w-30_1_synthetic  0.930
29        fdrive    korson_5w-30_1_synthetic  0.948

In [36]:
display(results_df)

,sku_1,sku_2,name_1,name_2,source_1,source_2,group,score
0,carcity:612978,fdrive_oil:17137,Моторное масло Синтетическое Bardahl ХTRA 5W-3...,Синтетическое моторное масло Bardahl XTC 5W-30 5L,carcity,fdrive,bardahl_5w-30_5_synthetic,0.967
1,carcity:713057,fdrive_oil:17137,Моторное масло Синтетическое Bardahl XTC 5W-30...,Синтетическое моторное масло Bardahl XTC 5W-30 5L,carcity,fdrive,bardahl_5w-30_5_synthetic,0.990
2,satu_kz:108008416,forte_market:97a92733-a5b2-11f0-8eaa-323109c6e470,Моторное масло Castrol Vecton Long Drain 10W-4...,Castrol Vecton Long Drain E6/E9 10W-40 208L,satu_kz,forte_market,castrol_10w-40_208_unknown,0.852
3,satu_kz:107304109,forte_market:c4be1c01-4478-11f1-bb9f-926e19253b23,Моторное масло Castrol Vecton 10W-40 E7 208 л,Castrol Magnatec A3/B4 10W-40 208L,satu_kz,forte_market,castrol_10w-40_208_unknown,0.720
4,satu_kz:107252062,forte_market:c4be1c01-4478-11f1-bb9f-926e19253b23,Моторное масло Castrol crb turbomax 10W-40 E4/...,Castrol Magnatec A3/B4 10W-40 208L,satu_kz,forte_market,castrol_10w-40_208_unknown,0.704
...,...,...,...,...,...,...,...,...
718,carcity:102768,fdrive_oil:17060,ATF CVTF MULTI-TYPE 4л (авт. транс. синт. масло),"ATF Type T-IV 4л (авт. транс. масло), Totachi",carcity,fdrive,totachi_unknown_4_unknown,0.895
719,carcity:102768,fdrive_oil:17062,ATF CVTF MULTI-TYPE 4л (авт. транс. синт. масло),"ATF Z-1 4л (авт. транс. синт. масло), Totachi",carcity,fdrive,totachi_unknown_4_unknown,0.824
720,carcity:102768,fdrive_oil:17067,ATF CVTF MULTI-TYPE 4л (авт. транс. синт. масло),ATF MULTI-VEHICLE 4л (авт. транс. синт. масло)...,carcity,fdrive,totachi_unknown_4_unknown,0.866
721,carcity:102768,fdrive_oil:17069,ATF CVTF MULTI-TYPE 4л (авт. транс. синт. масло),ATF Dex-III (class) 4л (авт. транс. синт. масл...,carcity,fdrive,totachi_unknown_4_unknown,0.830
722,carcity:102768,fdrive_oil:17061,ATF CVTF MULTI-TYPE 4л (авт. транс. синт. масло),"ATF Z-1 1л (авт. транс. синт. масло), Totachi",carcity,fdrive,totachi_unknown_4_unknown,0.786

In [37]:
def get_confidence(score):
    if score >= 0.9:
        return "HIGH"
    elif score >= 0.75:
        return "MEDIUM"
    else:
        return "LOW"

results_df["confidence"] = results_df["score"].apply(get_confidence)
print(results_df["confidence"].value_counts())

confidence
MEDIUM    510
HIGH      157
LOW        56
Name: count, dtype: int64

In [38]:
results_df = results_df.drop_duplicates(subset=["sku_1", "sku_2"])
print(results_df.shape)

(395, 9)

In [39]:
tyres_df = df[df["category_clean"] == "tyres"].copy()
print(tyres_df.shape)
print(tyres_df[["brand", "width", "profile", "diameter", "season"]].notna().sum())

(153691, 18)
brand       153627
width       150159
profile     149823
diameter    150288
season      147936
dtype: int64

In [40]:
tyres_df["brand_clean"] = tyres_df["brand"].fillna("unknown").str.lower().str.strip()
tyres_df["width_clean"] = tyres_df["width"].fillna("unknown").astype(str).str.lower().str.strip()
tyres_df["profile_clean"] = tyres_df["profile"].fillna("unknown").astype(str).str.lower().str.strip()
tyres_df["diameter_clean"] = tyres_df["diameter"].fillna("unknown").astype(str).str.lower().str.strip()
tyres_df["season_clean"] = tyres_df["season"].fillna("unknown").str.lower().str.strip()

tyres_df["group_key"] = (
    tyres_df["brand_clean"] + "_" +
    tyres_df["width_clean"] + "_" +
    tyres_df["profile_clean"] + "_" +
    tyres_df["diameter_clean"] + "_" +
    tyres_df["season_clean"]
)

print("Всего групп:", tyres_df["group_key"].nunique())
print(tyres_df["group_key"].value_counts())

Всего групп: 54831
group_key
maxxis_unknown_unknown_unknown_летняя                  145
petlas_unknown_unknown_unknown_unknown                 110
bkt_unknown_unknown_unknown_всесезонная                105
kenda_unknown_unknown_unknown_летняя                    96
mickey thompson_unknown_unknown_unknown_всесезонная     84
                                                      ...
петрошина_unknown_unknown_26"_unknown                    1
g&l_unknown_unknown_25"_unknown                          1
unknown_unknown_unknown_28"_unknown                      1
mrt_unknown_unknown_unknown_unknown                      1
gold_190 мм_unknown_unknown_unknown                      1
Name: count, Length: 54831, dtype: int64

In [41]:
print("width примеры:")
print(tyres_df["width"].dropna().unique()[:1000])

print("\ndiameter примеры:")
print(tyres_df["diameter"].dropna().unique()[:1000])

print("\nseason примеры:")
print(tyres_df["season"].dropna().unique()[:1000])

width примеры:
['205' '185' '17.5' '6.50' '175' '23.5' '315' '385' '7.50' '12.00' '70'
 '16.9' '65; 385' '9.5' '215' '12' '80; 12.5' '55; 385' '9' '7.00' '9.00'
 '80; 13' '8.15' '80; 320/80' '80; 440' '11.00' '10' '10.00' '275' '28.1'
 '18.4' '10.5' '620' '710' '80' '15.5' '13.6' '60; 315' '520' '70; 315'
 '14.00' '50; 435' '75; 215' '16.00' '13.00' '75; 205' '225' '285' '235'
 '195' '295' '265' '245' '255' '155' '165' '325' '305' '425' '650' '145'
 '445' '420' '530' '135' '395' '360' '500' '560' '380' '400' '260' '335'
 '320' '600' '33' '31' '32' '7' '35' '34' '6' '13' '11' '5' '8' '14' '15'
 '23' '30' '16' '18' '28' '1220' '26' '17' '435' '1025' '21' '355' '110'
 '4' '280' '279' '455' '104' '109' '107' '113' '115' '116' '120' '119'
 '140' '130' '37' '150' '27' '29' '160' '180' '190' '100' '170' '3' '108'
 '90' '200' '345' '365' '2' '240' '176' '125' '250' '25' '75' '55' '550'
 '45' '114' '60' '226' '95' '102' '495' '375' '112' '206' '85' '105' '106'
 '118' '525' '24' '121' '263' '700' '800' '19' '20' '22' '152' '300'
 '1200' '1300' '390' '480' '38' '340' '580' '440' '270' '900' '460' '405'
 '126' '123' '162' '210' '42' '720' '230' '1100' '7.5' '33.12' '35.12'
 '6.5' '155 мм' '260 мм' '235 мм' '4.1"' '425 мм' '540 мм' '285 мм'
 '245 мм' '240 мм' '205 мм' '750 мм' '325 мм' '195 мм' '135 мм' '395 мм'
 '480 мм' '315 мм' '460 мм' '420 мм' '210 мм' '130 мм' '23.5"' '300 мм'
 '265 мм' '230 мм' '375 мм' '200 мм' '1200 мм' '345 мм' '225 мм' '150 мм'
 '280 мм' '1100 мм' '21"' '215 мм' '275 мм' '295 мм' '3.50"' '16.9"' '587'
 '264' '140 мм' '16"' '467' '650 мм' '320 мм' '418мм' '850 мм' '292'
 '360 мм' '800 мм' '380 мм' '137' '18.4"' '8.25"' '12"' '12.4"' '6.50"'
 '18"' '10"' '710 мм' '520 мм' '15.5"' '30,5"' '21.3"' '6"' '185 мм'
 '9.5"' '5"' '6.5"' '7.5"' '7"' '8"' '8.3"' '11.2"' '14.9"' '175 мм'
 '13.6"' '1.4' '30.5"' '23.1"' '20.8"' '1.9' '900 мм' '218' '4.60 мм' '4"'
 '24.5"' '11.5"' '10.5"' '16.5"' '12.5"' '13"' '14"' '17.5"' '20.5"'
 '26.5"' '255 мм' '220 мм' '100 мм' '190 мм']

diameter примеры:
['R15' 'R25' 'R10' 'R13' 'R22.5' 'R16' 'R20' 'R24' 'R14' 'R28; 28'
 'R25; 17.5' 'R22; R22.5' 'R42' 'R22' 'R24; 24' 'R18; 18' 'R16; 16.5'
 'R12' 'R20; 20' 'R30; 30' 'R25; 23.5' 'R32' 'R26' 'R38' 'R30' 'R34' 'R0'
 'R18' 'R28' 'R17' 'R19; R19.5' 'R17; R17.5' 'R21' 'R19' 'R23' '16' '17'
 '18' '15' '13' '14' '19' '20' '21' '22' '19.5' '12' '23' '22.5' '17.5'
 '25' '24' '38' '42' '16.5' '508' '32' '46' '26' '28' '34' '533' '10' '9'
 '15.3' '15.5' '8' '33' '24.5' '102' '100' '106' '4' '11' '91' '95' '104'
 '5' '10.5' '18.5' '99' '90' '105' '20.5' '25.5' '26.5' '6.5' '103' '108'
 '6' '36' '54' '30' '44' '52' '7' '14.5' '665' '12.5' '15.5"' '20"'
 '17.5"' '21"' '12"' '24"' '17"' '16"' '32"' '26"' '42"' '38"' '18"' '15"'
 '25"' '30"' '34"' '22.5"' '9"' '19.5"' '28"' '15.3"' '10"' '16.5"' '36"'
 '65"' '26.5"' '33"' '19"' '6"' '14"' '13"' '8"']

season примеры:
['winter' 'Всесезонные шины' 'всесезонная' 'summer' 'all_season' 'Летняя'
 'Зимняя' 'Всесезонная' 'allseason' 'Летние шины'
 'Зимние нешипованные шины' 'Зимние шипованные шины' 'Зимние шины под шип'
 'Зимние шины']

In [42]:
def clean_width(val):
    if pd.isna(val):
        return "unknown"
    val = str(val).lower().strip()
    val = val.replace("мм", "").replace('"', "").replace("'", "").strip()
    # берём только первое число если есть ";"
    val = val.split(";")[0].strip()
    try:
        return str(round(float(val)))
    except:
        return "unknown"

def clean_diameter(val):
    if pd.isna(val):
        return "unknown"
    val = str(val).lower().strip()
    val = val.replace("r", "").replace('"', "").replace("'", "").strip()
    val = val.split(";")[0].strip()
    try:
        return str(round(float(val)))
    except:
        return "unknown"

def clean_season(val):
    if pd.isna(val):
        return "unknown"
    val = str(val).lower().strip()
    if any(w in val for w in ["winter", "зимн", "шип"]):
        return "winter"
    elif any(w in val for w in ["summer", "летн"]):
        return "summer"
    elif any(w in val for w in ["all", "всесез"]):
        return "allseason"
    return "unknown"

def extract_model(name):
    if pd.isna(name):
        return "unknown"
    name = str(name).lower().strip()
    # убираем размер типа 225/75 r16
    name = re.sub(r'\d+/\d+\s*r\d+', '', name)
    # убираем индексы нагрузки и скорости
    name = re.sub(r'\d+[a-z]$', '', name)
    # берём слова после бренда
    words = name.split()
    if len(words) > 1:
        return " ".join(words[1:3]).strip()
    return "unknown"

tyres_df["model_clean"] = tyres_df["name_clean"].apply(extract_model)

tyres_df["group_key"] = (
    tyres_df["brand_clean"] + "_" +
    tyres_df["model_clean"] + "_" +
    tyres_df["width_clean"] + "_" +
    tyres_df["profile_clean"] + "_" +
    tyres_df["diameter_clean"] + "_" +
    tyres_df["season_clean"]
)

print("Всего групп:", tyres_df["group_key"].nunique())

Всего групп: 101150

In [43]:
tyres_results2 = []

for group_key, group in tyres_df.groupby("group_key"):
    if len(group) < 2:
        continue
    if group["source"].nunique() < 2:
        continue
    if "unknown" in group_key:
        continue
    
    names = group["name_clean"].tolist()
    embeddings = model.encode(names)
    sim_matrix = cosine_similarity(embeddings)
    
    indices = group.index.tolist()
    for i in range(len(indices)):
        for j in range(i+1, len(indices)):
            if group.iloc[i]["source"] == group.iloc[j]["source"]:
                continue
            score = sim_matrix[i][j]
            if score > 0.7:
                tyres_results2.append({
                    "sku_1": group.iloc[i]["sku_id"],
                    "sku_2": group.iloc[j]["sku_id"],
                    "name_1": group.iloc[i]["normalized_name"],
                    "name_2": group.iloc[j]["normalized_name"],
                    "source_1": group.iloc[i]["source"],
                    "source_2": group.iloc[j]["source"],
                    "group": group_key,
                    "score": round(score, 3)
                })

tyres_results_df2 = pd.DataFrame(tyres_results2)
tyres_results_df2 = tyres_results_df2.drop_duplicates(subset=["sku_1", "sku_2"])
print(tyres_results_df2.shape)
print(tyres_results_df2.tail(10))

(4404, 8)
               sku_1                                              sku_2  \
5262  carcity:925110  pitstop:tyre/belshina/artmotion-snow/185-60-15...
5263  carcity:923083  pitstop:tyre/belshina/artmotion-snow/185-60-15...
5264  carcity:923083  pitstop:tyre/belshina/artmotion-snow/185-60-15...
5265  carcity:923083  pitstop:tyre/belshina/artmotion-snow/185-60-15...
5266  carcity:720987  pitstop:tyre/belshina/artmotion-snow/185-70-14...
5267  carcity:790926  pitstop:tyre/belshina/artmotion-snow/205-65-15...
5268  carcity:750429     pitstop:tyre/belshina/bel-264/175-65-14-82-h--
5269  carcity:468304     pitstop:tyre/belshina/bel-287/185-65-15-88-t--
5270  carcity:869115           pitstop:sh/belshina/bel-89/360-70-24----
5271  carcity:620847           pitstop:sh/belshina/bel-89/360-70-24----

                                                 name_1  \
5262  Белшина Artmotion Snow Бел-327 185/60 R15 84T ...
5263  Белшина Artmotion Snow Бел-367 185/60 R15 88T ...
5264  Белшина Artmotion Snow Бел-367 185/60 R15 88T ...
5265  Белшина Artmotion Snow Бел-367 185/60 R15 88T ...
5266  BELSHINA Artmotion Snow BEL-397 185/70 R14 88 ...
5267  Белшина Artmotion Snow Бел-297 205/65 R15 94T ...
5268                     Белшина Бел-264 175/65 R14 82H
5269          BELSHINA Бел-287 185/65 R15 88T без шипов
5270   Белшина БЕЛ-89 СЕР 360/70 R24C 129 A8  без шипов
5271                    Белшина Бел-89 360/70 R24 130A8

                                     name_2 source_1     source_2  \
5262  Белшина Artmotion Snow 185/60 R15 88T  carcity  pitstopshop
5263  Белшина Artmotion Snow 185/60 R15 84T  carcity  pitstopshop
5264  Белшина Artmotion Snow 185/60 R15 84H  carcity  pitstopshop
5265  Белшина Artmotion Snow 185/60 R15 88T  carcity  pitstopshop
5266  Белшина Artmotion Snow 185/70 R14 88T  carcity  pitstopshop
5267  Белшина Artmotion Snow 205/65 R15 94T  carcity  pitstopshop
5268         Белшина Бел 264 175/65 R14 82H  carcity  pitstopshop
5269         Белшина Бел-287 185/65 R15 88T  carcity  pitstopshop
5270              Белшина Бел-89 360/70 R24  carcity  pitstopshop
5271              Белшина Бел-89 360/70 R24  carcity  pitstopshop

                                        group  score
5262  белшина_artmotion snow_185_60_15_зимняя  0.928
5263  белшина_artmotion snow_185_60_15_зимняя  0.931
5264  белшина_artmotion snow_185_60_15_зимняя  0.905
5265  белшина_artmotion snow_185_60_15_зимняя  0.943
5266  белшина_artmotion snow_185_70_14_зимняя  0.862
5267  белшина_artmotion snow_205_65_15_зимняя  0.934
5268         белшина_бел 264_175_65_14_летняя  1.000
5269         белшина_бел 287_185_65_15_зимняя  0.876
5270     белшина_бел 89_360_70_24_всесезонная  0.808
5271     белшина_бел 89_360_70_24_всесезонная  0.977

In [44]:
display(tyres_results_df2)

,sku_1,sku_2,name_1,name_2,source_1,source_2,group,score
0,carcity:716078,pitstop:tyre/amtel/nordmaster-evo/195-65-15-91...,Amtel NordMaster Evo 195/65 R15 91T с шипами,Amtel NordMaster Evo 195/65 R15 91T,carcity,pitstopshop,amtel_nordmaster evo_195_65_15_зимняя,0.954
1,carcity:716078,pitstop:tyre/amtel/nordmaster-evo/195-65-15----,Amtel NordMaster Evo 195/65 R15 91T с шипами,Amtel NordMaster Evo 195/65 R15,carcity,pitstopshop,amtel_nordmaster evo_195_65_15_зимняя,0.936
2,carcity:716078,pitstop:tyre/amtel/nordmaster-evo/195-65-15-65...,Amtel NordMaster Evo 195/65 R15 91T с шипами,Amtel NordMaster Evo 195/65 R15 65T,carcity,pitstopshop,amtel_nordmaster evo_195_65_15_зимняя,0.957
3,carcity:716078,pitstop:tyre/amtel/nordmaster-evo/195-65-15--t--,Amtel NordMaster Evo 195/65 R15 91T с шипами,Amtel NordMaster Evo 195/65 R15 T,carcity,pitstopshop,amtel_nordmaster evo_195_65_15_зимняя,0.943
4,carcity:1255427,pitstop:tyre/arivo/ice-claw-arw4/185-60-15-88-...,Arivo ICE CLAW ARW4 185/60 R15 88 T с шипами,Arivo Ice Claw ARW4 185/60 R15 88T XL,carcity,pitstopshop,arivo_ice claw_185_60_15_зимняя,0.977
...,...,...,...,...,...,...,...,...
5267,carcity:790926,pitstop:tyre/belshina/artmotion-snow/205-65-15...,Белшина Artmotion Snow Бел-297 205/65 R15 94T ...,Белшина Artmotion Snow 205/65 R15 94T,carcity,pitstopshop,белшина_artmotion snow_205_65_15_зимняя,0.934
5268,carcity:750429,pitstop:tyre/belshina/bel-264/175-65-14-82-h--,Белшина Бел-264 175/65 R14 82H,Белшина Бел 264 175/65 R14 82H,carcity,pitstopshop,белшина_бел 264_175_65_14_летняя,1.000
5269,carcity:468304,pitstop:tyre/belshina/bel-287/185-65-15-88-t--,BELSHINA Бел-287 185/65 R15 88T без шипов,Белшина Бел-287 185/65 R15 88T,carcity,pitstopshop,белшина_бел 287_185_65_15_зимняя,0.876
5270,carcity:869115,pitstop:sh/belshina/bel-89/360-70-24----,Белшина БЕЛ-89 СЕР 360/70 R24C 129 A8 без шипов,Белшина Бел-89 360/70 R24,carcity,pitstopshop,белшина_бел 89_360_70_24_всесезонная,0.808
5271,carcity:620847,pitstop:sh/belshina/bel-89/360-70-24----,Белшина Бел-89 360/70 R24 130A8,Белшина Бел-89 360/70 R24,carcity,pitstopshop,белшина_бел 89_360_70_24_всесезонная,0.977

In [45]:
filters_df = df[df["category_clean"] == "filters"].copy()
print(filters_df.shape)
print(filters_df[["brand", "filter_type", "oem_number"]].notna().sum())

(35084, 18)
brand          35084
filter_type    34880
oem_number     26716
dtype: int64

In [46]:
#Cleaning
filters_df = df[df["category_clean"] == "filters"].copy()

filters_df["brand_clean"] = filters_df["brand"].fillna("unknown").str.lower().str.strip()
filters_df["filter_type_clean"] = filters_df["filter_type"].fillna("unknown").str.lower().str.strip()
filters_df["oem_clean"] = (
    filters_df["oem_number"]
    .fillna("unknown")
    .str.lower()
    .str.strip()
    .str.replace(" ", "")
    .str.replace("-", "")
)

print("filter_type values:")
print(filters_df["filter_type_clean"].value_counts())
print("\noem заполнено:", (filters_df["oem_clean"] != "unknown").sum())

filter_type values:
filter_type_clean
воздушный                                      11556
масляный                                        7603
салонный                                        6399
топливный                                       6232
air                                              879
трансмиссионный                                  690
oil                                              679
fuel                                             371
cabin                                            311
unknown                                          204
гидравлический                                   156
fuel; топливные фильтры для бензиновых авто        2
fuel; топливные фильтры для дизельных авто         1
air; воздушные фильтры для легк. авто              1
Name: count, dtype: int64

oem заполнено: 26716

In [47]:
def clean_filter_type(val):
    if pd.isna(val):
        return "unknown"
    val = str(val).lower().strip()
    if any(w in val for w in ["воздушный", "air"]):
        return "air"
    elif any(w in val for w in ["масляный", "oil"]):
        return "oil"
    elif any(w in val for w in ["салонный", "cabin"]):
        return "cabin"
    elif any(w in val for w in ["топливный", "fuel"]):
        return "fuel"
    elif "трансмиссионный" in val:
        return "transmission"
    elif "гидравлический" in val:
        return "hydraulic"
    return "unknown"

filters_df["filter_type_clean"] = filters_df["filter_type"].apply(clean_filter_type)
print(filters_df["filter_type_clean"].value_counts())

filter_type_clean
air             12436
oil              8282
cabin            6710
fuel             6606
transmission      690
unknown           204
hydraulic         156
Name: count, dtype: int64

In [48]:
oem_matches = []
oem_df = filters_df[filters_df["oem_clean"] != "unknown"]

for oem, group in oem_df.groupby("oem_clean"):
    if len(group) < 2:
        continue
    if group["source"].nunique() < 2:
        continue
    for i in range(len(group)):
        for j in range(i+1, len(group)):
            if group.iloc[i]["source"] == group.iloc[j]["source"]:
                continue
            oem_matches.append({
                "sku_1": group.iloc[i]["sku_id"],
                "sku_2": group.iloc[j]["sku_id"],
                "name_1": group.iloc[i]["normalized_name"],
                "name_2": group.iloc[j]["normalized_name"],
                "oem_1": group.iloc[i]["oem_clean"],
                "oem_2": group.iloc[j]["oem_clean"],
                "source_1": group.iloc[i]["source"],
                "source_2": group.iloc[j]["source"],
                "score": 1.0,
                "match_type": "OEM"
            })

oem_results_df = pd.DataFrame(oem_matches).drop_duplicates(subset=["sku_1", "sku_2"])
print("OEM matches:", len(oem_results_df))
print(oem_results_df[["name_1", "name_2", "oem_1", "oem_2", "score"]].head(5))

OEM matches: 23
                         name_1                               name_2  \
0  Фильтр воздушный 16546-0509R  MANN-FILTER воздушный фильтр C27030
1  Фильтр воздушный 16546-0509R       Sufix воздушный фильтр SO-1047
4  Фильтр воздушный 16546-0509R   BIG FILTER воздушный фильтр GB-962
5  Фильтр воздушный 16546-0509R                     Воздушный фильтр
7  Фильтр воздушный 17801-0L040   JS Asakashi воздушный фильтр A1531

        oem_1       oem_2  score
0  165460509r  165460509r    1.0
1  165460509r  165460509r    1.0
4  165460509r  165460509r    1.0
5  165460509r  165460509r    1.0
7  178010l040  178010l040    1.0

In [49]:
def extract_article(name):
    if pd.isna(name):
        return "unknown"
    matches = re.findall(r'[A-Z]{2,}[\d]+[A-Z\d]*', str(name))
    if matches:
        return matches[-1].lower()
    return "unknown"

filters_df["article"] = filters_df["normalized_name"].apply(extract_article)

filters_df["group_key"] = (
    filters_df["brand_clean"] + "_" +
    filters_df["filter_type_clean"] + "_" +
    filters_df["article"]
)

print(filters_df["article"].value_counts().head(10))

nlp_matches = []

for group_key, group in filters_df.groupby("group_key"):
    if len(group) < 2:
        continue
    if group["source"].nunique() < 2:
        continue
    if "unknown" in group_key:
        continue
    if len(group) > 30:  # пропускаем огромные группы
        continue

    names = group["name_clean"].tolist()
    embeddings = model.encode(names, batch_size=64, show_progress_bar=False)
    sim_matrix = cosine_similarity(embeddings)

    for i in range(len(group)):
        for j in range(i+1, len(group)):
            if group.iloc[i]["source"] == group.iloc[j]["source"]:
                continue
            score = sim_matrix[i][j]
            if score > 0.75:
                nlp_matches.append({
                    "sku_1": group.iloc[i]["sku_id"],
                    "sku_2": group.iloc[j]["sku_id"],
                    "name_1": group.iloc[i]["normalized_name"],
                    "name_2": group.iloc[j]["normalized_name"],
                    "oem": group.iloc[i]["oem_clean"],
                    "source_1": group.iloc[i]["source"],
                    "source_2": group.iloc[j]["source"],
                    "score": round(score, 3),
                    "match_type": "NLP"
                })

nlp_results_df = pd.DataFrame(nlp_matches).drop_duplicates(subset=["sku_1", "sku_2"])
print("NLP matches:", len(nlp_results_df))

article
unknown    25217
hu719         21
wk820         19
ix35          16
wk950         15
rav4          15
wk842         14
hu718         12
wk69          12
hu711         12
Name: count, dtype: int64
NLP matches: 838

In [50]:
oem_results_df

,sku_1,sku_2,name_1,name_2,oem_1,oem_2,source_1,source_2,score,match_type
0,satu_kz:126724226,carcity:943201,Фильтр воздушный 16546-0509R,MANN-FILTER воздушный фильтр C27030,165460509r,165460509r,satu_kz,carcity,1.0,OEM
1,satu_kz:126724226,carcity:937947,Фильтр воздушный 16546-0509R,Sufix воздушный фильтр SO-1047,165460509r,165460509r,satu_kz,carcity,1.0,OEM
4,satu_kz:126724226,carcity:650059,Фильтр воздушный 16546-0509R,BIG FILTER воздушный фильтр GB-962,165460509r,165460509r,satu_kz,carcity,1.0,OEM
5,satu_kz:126724226,carcity:22071,Фильтр воздушный 16546-0509R,Воздушный фильтр,165460509r,165460509r,satu_kz,carcity,1.0,OEM
7,satu_kz:126723955,carcity:971790,Фильтр воздушный 17801-0L040,JS Asakashi воздушный фильтр A1531,178010l040,178010l040,satu_kz,carcity,1.0,OEM
9,satu_kz:126723955,carcity:980600,Фильтр воздушный 17801-0L040,Japanparts воздушный фильтр fa2016s,178010l040,178010l040,satu_kz,carcity,1.0,OEM
12,satu_kz:126724334,carcity:943914,Фильтр салона 272773016R,SCT салонный фильтр SA 1324,272773016r,272773016r,satu_kz,carcity,1.0,OEM
15,satu_kz:126724334,carcity:945076,Фильтр салона 272773016R,MFilter салонный фильтр K9104,272773016r,272773016r,satu_kz,carcity,1.0,OEM
18,satu_kz:126724334,carcity:937936,Фильтр салона 272773016R,MANN-FILTER салонный фильтр CU22011,272773016r,272773016r,satu_kz,carcity,1.0,OEM
22,satu_kz:126882549,carcity:672754,Фильтр салона 27277-4BU0A,FILTRON салонный фильтр K1355,272774bu0a,272774bu0a,satu_kz,carcity,1.0,OEM
24,satu_kz:126882549,carcity:943475,Фильтр салона 27277-4BU0A,Blue Print салонный фильтр ADN12539,272774bu0a,272774bu0a,satu_kz,carcity,1.0,OEM
25,satu_kz:126882549,carcity:944172,Фильтр салона 27277-4BU0A,FRAM салонный фильтр CF11854,272774bu0a,272774bu0a,satu_kz,carcity,1.0,OEM
28,satu_kz:126882549,carcity:938910,Фильтр салона 27277-4BU0A,Sufix салонный фильтр SS-1194,272774bu0a,272774bu0a,satu_kz,carcity,1.0,OEM
31,satu_kz:126882549,carcity:954133,Фильтр салона 27277-4BU0A,MANN-FILTER салонный фильтр CU25003,272774bu0a,272774bu0a,satu_kz,carcity,1.0,OEM
34,satu_kz:126858755,carcity:662531,Фильтр салона 27277-EN000 Nissan Qashqai x-trail,Фильтр салонный Winkod WC4017,27277en000,27277en000,satu_kz,carcity,1.0,OEM
37,satu_kz:132261842,carcity:1306436,Салонный фильтр VW Polo DeliParts 6R0820367,"Фильтр, воздух во внутреннем пространстве 8000...",6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
38,satu_kz:132261842,carcity:653520,Салонный фильтр VW Polo DeliParts 6R0820367,SCT салонный фильтр SA 1291,6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
41,satu_kz:132261842,carcity:895516,Салонный фильтр VW Polo DeliParts 6R0820367,MFilter салонный фильтр K 9069,6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
42,satu_kz:132261842,carcity:657978,Салонный фильтр VW Polo DeliParts 6R0820367,Winkod салонный WC4006,6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
43,satu_kz:132261842,carcity:652206,Салонный фильтр VW Polo DeliParts 6R0820367,SAT салонный фильтр ST-6R0820367,6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
45,satu_kz:132261842,carcity:1025052,Салонный фильтр VW Polo DeliParts 6R0820367,MANN-FILTER салонный фильтр CU26010,6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
48,satu_kz:132261842,carcity:1027763,Салонный фильтр VW Polo DeliParts 6R0820367,FILTRON салонный фильтр K1313,6r0820367,6r0820367,satu_kz,carcity,1.0,OEM
51,satu_kz:132261755,carcity:1270881,Салонный фильтр Omoda c5 DeliParts ZJP-CY5000055,фильтр салона угол.\Chery Tiggo 4 19-20,zjpcy5000055,zjpcy5000055,satu_kz,carcity,1.0,OEM

In [51]:
nlp_results_df

,sku_1,sku_2,name_1,name_2,oem,source_1,source_2,score,match_type
0,forte_market:d7c26033-1918-11f0-98dc-52a30f980d2f,carcity:940655,Amd Воздушный AMDFA15,AMD воздушный фильтр AMDFA15,unknown,forte_market,carcity,0.871,NLP
3,forte_market:02f92f4e-1918-11f0-98dc-52a30f980d2f,carcity:896389,Amd Воздушный AMDFA412,AMD воздушный фильтр AMDFA412,unknown,forte_market,carcity,0.892,NLP
4,forte_market:e252d9e4-1917-11f0-98dc-52a30f980d2f,carcity:984598,Amd Воздушный AMDJFA116,AMD воздушный фильтр AMDJFA116,unknown,forte_market,carcity,0.871,NLP
5,forte_market:0af3b1be-1918-11f0-98dc-52a30f980d2f,carcity:1035378,Amd Салонный AMDFC21,AMD салонный фильтр AMDFC21,unknown,forte_market,carcity,0.862,NLP
7,forte_market:986a15b8-1915-11f0-98dc-52a30f980d2f,carcity:923629,Aobi Воздушный ZA0470,AOBI воздушный фильтр ZA0470,unknown,forte_market,carcity,0.891,NLP
...,...,...,...,...,...,...,...,...,...
1969,forte_market:bb0423c8-1915-11f0-98dc-52a30f980d2f,carcity:958735,Winkod Масляный WO1970,Winkod масляный фильтр WO1970,unknown,forte_market,carcity,0.864,NLP
1971,forte_market:c2d3b4d2-1915-11f0-98dc-52a30f980d2f,carcity:1030142,Winkod Масляный WO1974,Масляный фильтр Winkod WO1974,unknown,forte_market,carcity,0.829,NLP
1973,forte_market:b23e0e3a-1915-11f0-98dc-52a30f980d2f,carcity:1029478,Winkod Масляный WO1977,Winkod масляный фильтр WO1977,unknown,forte_market,carcity,0.857,NLP
1975,forte_market:2eb76230-1918-11f0-98dc-52a30f980d2f,carcity:1024803,Winkod Масляный WO1979,Winkod масляный фильтр WO1979,unknown,forte_market,carcity,0.845,NLP
1976,forte_market:0aec7082-1914-11f0-98dc-52a30f980d2f,carcity:664963,Winkod Масляный WO1984,Winkod масляный фильтр WO1984,unknown,forte_market,carcity,0.880,NLP

In [52]:
batteries_df = df[df["category_clean"] == "batteries"].copy()
print(batteries_df.shape)
print(batteries_df[["brand", "capacity_ah", "voltage_v"]].notna().sum())

(522, 18)
brand          522
capacity_ah    490
voltage_v      183
dtype: int64

In [53]:
batteries_df.isnull().sum()

sku_id               0
source               0
product_name         0
normalized_name      0
category             0
brand                0
viscosity          522
volume             522
width              522
profile            522
diameter           522
season             522
filter_type        522
oem_number         477
capacity_ah         32
voltage_v          339
category_clean       0
name_clean           0
dtype: int64

In [ ]:
batteries_df["group_key"] = (
    batteries_df["brand_clean"] + "_" +
    batteries_df["capacity_clean"]
)

battery_results = []

for group_key, group in batteries_df.groupby("group_key"):
    if len(group) < 2:
        continue
    if group["source"].nunique() < 2:
        continue
    if "unknown" in group_key:
        continue

    names = group["name_clean"].tolist()
    embeddings = model.encode(names, batch_size=64, show_progress_bar=False)
    sim_matrix = cosine_similarity(embeddings)

    for i in range(len(group)):
        for j in range(i+1, len(group)):
            if group.iloc[i]["source"] == group.iloc[j]["source"]:
                continue
            score = sim_matrix[i][j]
            if score > 0.75:
                battery_results.append({
                    "sku_1": group.iloc[i]["sku_id"],
                    "sku_2": group.iloc[j]["sku_id"],
                    "name_1": group.iloc[i]["normalized_name"],
                    "name_2": group.iloc[j]["normalized_name"],
                    "source_1": group.iloc[i]["source"],
                    "source_2": group.iloc[j]["source"],
                    "group": group_key,
                    "score": round(score, 3),
                    "match_type": "NLP"
                })

battery_results_df = pd.DataFrame(battery_results).drop_duplicates(subset=["sku_1", "sku_2"])
print("Battery matches:", len(battery_results_df))
print(battery_results_df.head(10))

In [55]:
print(batteries_df["source"].value_counts())

source
carcity         199
forte_market    179
satu_kz         144
Name: count, dtype: int64

In [56]:
print(batteries_df["capacity_ah"].unique()[:2000])
print(batteries_df["voltage_v"].unique()[:2000])

['60' '80' '70' '68' '40' '35' '74' '95' '45' '52' '61' '63' '72' '75'
 '100' '105' '110' '140' '180' '190' '225' '240' '42' '50' '65' '90' '230'
 '91' '12' '6' '5' '8' '10' '11' '13' '14' '18' '19' '20' '25' '30' '85'
 '38' nan '98' '16' '44' '55' '84' '77' '62' '51' '43' '135' '78' '92'
 '71' '64' '145' '125' '54']
[nan '12']

In [66]:
def extract_battery_model(name):
    if pd.isna(name):
        return "unknown"
    name = str(name).lower()
    matches = re.findall(r's\d+|silver|blue|black|asia|agm', name)
    if matches:
        return matches[0]
    return "unknown"

batteries_df["model_clean"] = batteries_df["normalized_name"].apply(extract_battery_model)

batteries_df["group_key"] = (
    batteries_df["brand_clean"] + "_" +
    batteries_df["model_clean"] + "_" +
    batteries_df["capacity_clean"]
)

print(batteries_df["model_clean"].value_counts())

for group_key, group in batteries_df.groupby("group_key"):
    if len(group) < 2:
        continue
    if group["source"].nunique() < 2:
        continue
    if "unknown" in group_key:
        continue

    names = group["name_clean"].tolist()
    embeddings = model.encode(names, batch_size=64, show_progress_bar=False)
    sim_matrix = cosine_similarity(embeddings)

    for i in range(len(group)):
        for j in range(i+1, len(group)):
            if group.iloc[i]["source"] == group.iloc[j]["source"]:
                continue
            score = sim_matrix[i][j]
            if score > 0.75:
                battery_results.append({
                    "sku_1": group.iloc[i]["sku_id"],
                    "sku_2": group.iloc[j]["sku_id"],
                    "name_1": group.iloc[i]["normalized_name"],
                    "name_2": group.iloc[j]["normalized_name"],
                    "source_1": group.iloc[i]["source"],
                    "source_2": group.iloc[j]["source"],
                    "group": group_key,
                    "score": round(score, 3),
                    "match_type": "NLP"
                })

battery_results_df = pd.DataFrame(battery_results).drop_duplicates(subset=["sku_1", "sku_2"])
print("Battery matches:", len(battery_results_df))
print(battery_results_df.head(10))

model_clean
unknown    336
silver      46
asia        42
agm         26
blue        25
s4          22
s5          12
s46          5
s55          4
black        1
s95          1
s50          1
s34          1
Name: count, dtype: int64
Battery matches: 88
                                                sku_1            sku_2  \
0   forte_market:b34446b0-b31c-11ef-a020-9e2dc40276a0  carcity:1196511
1   forte_market:6df07489-79bf-11f0-b5ca-a2e49f0a0e4b   carcity:412569
2                                    satu_kz:73772089  carcity:1317312
3                                    satu_kz:73772081    carcity:58917
4                                    satu_kz:73772082    carcity:58917
5                                    satu_kz:73772084    carcity:58918
6                                    satu_kz:72849754    carcity:73692
8                                    satu_kz:72849755    carcity:73681
9                                    satu_kz:72849757    carcity:73683
10                                   satu_kz:72849758    carcity:73684

                                               name_1  \
0                              Bars Asia +/- 42Ah 12V
1                      Bars 6CT- Silver Обратная 60Ah
2                        Аккумулятор BOSCH S5 A15 AGM
3                        Аккумулятор BOSCH S5 A11 AGM
4                            Аккумулятор BOSCH S4 010
5                        Аккумулятор BOSCH S5 A13 AGM
6   Аккумулятор Varta Silver Dynamic H3 100Ah 830A...
8   Аккумулятор Varta Silver Dynamic AGM H15 105Ah...
9   Аккумулятор Varta Promotive Blue K8 140Ah 800A...
10  Аккумулятор Varta Promotive Silver M18 180Ah 1...

                                               name_2      source_1 source_2  \
0             BARS B19 Asia 6CT-42Ah +/- 42 Ач прямая  forte_market  carcity
1   Аккумулятор BARS Silver 60Ah Silver 60Ah 60 об...  forte_market  carcity
2   Аккумулятор 105 ач обратная 950 а 12 в agm s5 ...       satu_kz  carcity
3   Аккумулятор 80 ач обратная 800 а 12 в agm s5 a...       satu_kz  carcity
4   Аккумулятор 80 ач обратная 800 а 12 в agm s5 a...       satu_kz  carcity
5   Аккумулятор 95 ач обратная 850 а 12 в agm star...       satu_kz  carcity
6   Батарея аккумуляторная VARTA Silver Dynamic 10...       satu_kz  carcity
8   VARTA Аккумулятор 105Ah 605901 "- +" 394x175x1...       satu_kz  carcity
9    VARTA Аккумулятор 140Ah 640400 "+ -" 513x189x223       satu_kz  carcity
10   VARTA Аккумулятор 180Ah 680108 "+ -" 513x223x223       satu_kz  carcity

        group  score match_type
0     bars_42  0.794        NLP
1     bars_60  0.753        NLP
2   bosch_105  0.848        NLP
3    bosch_80  0.850        NLP
4    bosch_80  0.785        NLP
5    bosch_95  0.781        NLP
6   varta_100  0.867        NLP
8   varta_105  0.892        NLP
9   varta_140  0.882        NLP
10  varta_180  0.839        NLP

In [67]:
battery_results_df

,sku_1,sku_2,name_1,name_2,source_1,source_2,group,score,match_type
0,forte_market:b34446b0-b31c-11ef-a020-9e2dc40276a0,carcity:1196511,Bars Asia +/- 42Ah 12V,BARS B19 Asia 6CT-42Ah +/- 42 Ач прямая,forte_market,carcity,bars_42,0.794,NLP
1,forte_market:6df07489-79bf-11f0-b5ca-a2e49f0a0e4b,carcity:412569,Bars 6CT- Silver Обратная 60Ah,Аккумулятор BARS Silver 60Ah Silver 60Ah 60 об...,forte_market,carcity,bars_60,0.753,NLP
2,satu_kz:73772089,carcity:1317312,Аккумулятор BOSCH S5 A15 AGM,Аккумулятор 105 ач обратная 950 а 12 в agm s5 ...,satu_kz,carcity,bosch_105,0.848,NLP
3,satu_kz:73772081,carcity:58917,Аккумулятор BOSCH S5 A11 AGM,Аккумулятор 80 ач обратная 800 а 12 в agm s5 a...,satu_kz,carcity,bosch_80,0.850,NLP
4,satu_kz:73772082,carcity:58917,Аккумулятор BOSCH S4 010,Аккумулятор 80 ач обратная 800 а 12 в agm s5 a...,satu_kz,carcity,bosch_80,0.785,NLP
...,...,...,...,...,...,...,...,...,...
132,satu_kz:72849753,carcity:73677,Аккумулятор Varta Blue Dynamic G7 95Ah 830A 30...,"VARTA Аккумулятор 95Ah 595404 ""- +"" 306x173x225",satu_kz,carcity,varta_95,0.867,NLP
134,satu_kz:72849753,carcity:73678,Аккумулятор Varta Blue Dynamic G7 95Ah 830A 30...,"VARTA Аккумулятор 95Ah 595405 ""+ -"" 306x173x225",satu_kz,carcity,varta_95,0.870,NLP
136,satu_kz:72849753,carcity:1342446,Аккумулятор Varta Blue Dynamic G7 95Ah 830A 30...,Аккумулятор автомобильный VARTA Blue Dynamic G3,satu_kz,carcity,varta_95,0.858,NLP
137,forte_market:d7dd8eda-b31e-11ef-a020-9e2dc40276a0,carcity:73712,Wewatt WT591400 +/- 91Ah,"Аккумулятор WEWATT WT591400 91Ah ""- +"" 306x173...",forte_market,carcity,wewatt_91,0.766,NLP
138,forte_market:c43ec177-b31c-11ef-a020-9e2dc40276a0,carcity:411697,Электра -/+ 60Ah 12V,Аккумулятор Электра 6СТ-60Ah -/+,forte_market,carcity,электра_60,0.773,NLP

In [68]:
all_filter_results = pd.concat([oem_results_df, nlp_results_df], ignore_index=True)
all_filter_results = all_filter_results.drop_duplicates(subset=["sku_1", "sku_2"])

In [69]:
results_df["category"] = "oils"
tyres_results_df2["category"] = "tyres"
all_filter_results ["category"] = "filters"
battery_results_df["category"] = "batteries"

final_results = pd.concat([
    results_df,
    tyres_results_df2,
    all_filter_results,
    battery_results_df
], ignore_index=True)

print("ИТОГО матчей:", len(final_results))
print(final_results["category"].value_counts())

ИТОГО матчей: 5748
category
tyres        4404
filters       861
oils          395
batteries      88
Name: count, dtype: int64

In [70]:
final_results.to_csv("matching_results.csv", index=False)
print("Сохранено!")
print(final_results.head(5))

Сохранено!
               sku_1                                              sku_2  \
0     carcity:612978                                   fdrive_oil:17137
1     carcity:713057                                   fdrive_oil:17137
2  satu_kz:108008416  forte_market:97a92733-a5b2-11f0-8eaa-323109c6e470
3  satu_kz:107304109  forte_market:c4be1c01-4478-11f1-bb9f-926e19253b23
4  satu_kz:107252062  forte_market:c4be1c01-4478-11f1-bb9f-926e19253b23

                                              name_1  \
0  Моторное масло Синтетическое Bardahl ХTRA 5W-3...
1  Моторное масло Синтетическое Bardahl XTC 5W-30...
2  Моторное масло Castrol Vecton Long Drain 10W-4...
3      Моторное масло Castrol Vecton 10W-40 E7 208 л
4  Моторное масло Castrol crb turbomax 10W-40 E4/...

                                              name_2 source_1      source_2  \
0  Синтетическое моторное масло Bardahl XTC 5W-30 5L  carcity        fdrive
1  Синтетическое моторное масло Bardahl XTC 5W-30 5L  carcity        fdrive
2        Castrol Vecton Long Drain E6/E9 10W-40 208L  satu_kz  forte_market
3                 Castrol Magnatec A3/B4 10W-40 208L  satu_kz  forte_market
4                 Castrol Magnatec A3/B4 10W-40 208L  satu_kz  forte_market

                        group  score confidence category oem_1 oem_2  \
0   bardahl_5w-30_5_synthetic  0.967       HIGH     oils   NaN   NaN
1   bardahl_5w-30_5_synthetic  0.990       HIGH     oils   NaN   NaN
2  castrol_10w-40_208_unknown  0.852     MEDIUM     oils   NaN   NaN
3  castrol_10w-40_208_unknown  0.720        LOW     oils   NaN   NaN
4  castrol_10w-40_208_unknown  0.704        LOW     oils   NaN   NaN

  match_type  oem
0        NaN  NaN
1        NaN  NaN
2        NaN  NaN
3        NaN  NaN
4        NaN  NaN